
services:
  luxstreet:
    image: wordpress:latest
    container_name: luxstreet-wordpress
    restart: always
    ports:
      - "4080:80"
    env_file: .env
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - sigma-net
    depends_on:
      - luxstreet-db

  luxstreet-db:
    image: mariadb:10.6
    container_name: luxstreet-db
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:4054:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sigma-net

volumes:
  db_data:

networks:
  sigma-net:
    external: true
